name: 'Lew L. Humiston, IV'
favicon: null
layout_spectrum: 1
typography_spectrum: 0.80354
title: 'Tortured Bard '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#151515'
    - '#f4f4f4'
    - '#515151'
    - '#7b7b7b'
    - '#b3b3b3'
  brandStrength: 0.3125
  lightness: 0.5625
  saturation: 0.875
  rhythmicContrast: 1
purpose: []
